development:
  host: localhost:8080
  email: bobby@cmnd-o.com
  password: 60-cmnd-0
  api_key: 0939f07ce38e3464d16238fe13796935bd430abc
staging:
  host: staging.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>
production:
  host: www.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>